/*

“Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, …

By considering the terms in the Fibonacci sequence whose values do not exceed four million, produce a JavaScript solution to find the sum of the even-valued terms.”

*/

function sumEvenFibonacciNumbers() {
  var stoppingCase = 4000000,
      operand1 = 1,
      operand2 = 1,
      fibSum = 0, 
      total = 0;
  while(fibSum < stoppingCase) {
    if(fibSum % 2 == 0) {
      console.log('adding: ', fibSum);
      total += fibSum;
    }
    fibSum = operand1 + operand2;
    operand1 = operand2;
    operand2 = fibSum;
  }
  console.log('stopping number: ', fibSum);
  console.log('total: ', total);
}

sumEvenFibonacciNumbers();
